version: 1
frontend:
  phases:
    preBuild:
      commands:
        - echo "No frontend build required"
    build:
      commands:
        - echo "No frontend build required"
  artifacts:
    baseDirectory: /
    files:
      - '**/*'
backend:
  phases:
    preBuild:
      commands:
        - npm install
    build:
      commands:
        - npm run build
  artifacts:
    baseDirectory: .
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
