version: 1
applications:
  - backend:
      phases:
        preBuild:
          commands:
            - npm install
        build:
          commands:
            - npm start
      cache:
        paths:
          - node_modules/**/*