version: 1
applications:
  - appRoot: .
    backend:
      phases:
        preBuild:
          commands:
            - npm install
        build:
          commands:
            - npm run build
      artifacts:
        baseDirectory: .
        files:
          - '**/*'
      cache:
        paths:
          - node_modules/**/*
